/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "string_tests_check/s21_strcspn_test.check"
 * instead.
 */

#include <check.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "../s21_string.h"

START_TEST(s21_strcspn_test_1) {
  char str1[] = "There is a destination string for checking!!!!";
  char str2[] = " ";
  size_t result = s21_strcspn(str1, str2);
  size_t result_etalon = strcspn(str1, str2);
  ck_assert_uint_eq(result, result_etalon);
}
END_TEST

START_TEST(s21_strcspn_test_2) {
  char str1[] = "There is a destination string for checking!!!!";
  char str2[] = "";
  size_t result = s21_strcspn(str1, str2);
  size_t result_etalon = strcspn(str1, str2);
  ck_assert_uint_eq(result, result_etalon);
}
END_TEST

START_TEST(s21_strcspn_test_3) {
  char str1[] = "";
  char str2[] = "";
  size_t result = s21_strcspn(str1, str2);
  size_t result_etalon = strcspn(str1, str2);
  ck_assert_uint_eq(result, result_etalon);
}
END_TEST

START_TEST(s21_strcspn_test_4) {
  char str1[] = " ";
  char str2[] = " ";
  size_t result = s21_strcspn(str1, str2);
  size_t result_etalon = strcspn(str1, str2);
  ck_assert_uint_eq(result, result_etalon);
}
END_TEST

START_TEST(s21_strcspn_test_5) {
  char str1[] = "\0";
  char str2[] = " ";
  size_t result = s21_strcspn(str1, str2);
  size_t result_etalon = strcspn(str1, str2);
  ck_assert_uint_eq(result, result_etalon);
}
END_TEST

START_TEST(s21_strcspn_test_6) {
  char str1[] = "";
  char str2[] = "\0 ";
  size_t result = s21_strcspn(str1, str2);
  size_t result_etalon = strcspn(str1, str2);
  ck_assert_uint_eq(result, result_etalon);
}
END_TEST

START_TEST(s21_strcspn_test_7) {
  char str1[] = "@#$%^&*()1234567890";
  char str2[] = "!";
  size_t result = s21_strcspn(str1, str2);
  size_t result_etalon = strcspn(str1, str2);
  ck_assert_uint_eq(result, result_etalon);
}
END_TEST

START_TEST(s21_strcspn_test_8) {
  char str1[] = "@#$%^&*()1234567890";
  char str2[] = "^";
  size_t result = s21_strcspn(str1, str2);
  size_t result_etalon = strcspn(str1, str2);
  ck_assert_uint_eq(result, result_etalon);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, s21_strcspn_test_1);
  tcase_add_test(tc1_1, s21_strcspn_test_2);
  tcase_add_test(tc1_1, s21_strcspn_test_3);
  tcase_add_test(tc1_1, s21_strcspn_test_4);
  tcase_add_test(tc1_1, s21_strcspn_test_5);
  tcase_add_test(tc1_1, s21_strcspn_test_6);
  tcase_add_test(tc1_1, s21_strcspn_test_7);
  tcase_add_test(tc1_1, s21_strcspn_test_8);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
