/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "string_tests_check/s21_strrchr_test.check"
 * instead.
 */

#include <check.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "../s21_string.h"

START_TEST(s21_strrchr_test_1) {
  char str[] = "There is a destination string for checking!!!!";
  char ch = 'c';
  char *result = s21_strrchr(str, ch);
  char *result_etalon = strrchr(str, ch);
  ck_assert_ptr_eq(result, result_etalon);
}
END_TEST

START_TEST(s21_strrchr_test_2) {
  char str[] = "\0";
  char ch = 'c';
  char *result = s21_strrchr(str, ch);
  char *result_etalon = strrchr(str, ch);
  ck_assert_ptr_eq(result, result_etalon);
}
END_TEST

START_TEST(s21_strrchr_test_3) {
  char str[] = "There is a destination string for checking!!!!";
  char ch = '\0';
  char *result = s21_strrchr(str, ch);
  char *result_etalon = strrchr(str, ch);
  ck_assert_ptr_eq(result, result_etalon);
}
END_TEST

START_TEST(s21_strrchr_test_4) {
  char str[] = "\0";
  char ch = '\0';
  char *result = s21_strrchr(str, ch);
  char *result_etalon = strrchr(str, ch);
  ck_assert_ptr_eq(result, result_etalon);
}
END_TEST

START_TEST(s21_strrchr_test_5) {
  char str[] = "There is a destination stri\0ng for checking!!!!";
  char ch = 'c';
  char *result = s21_strrchr(str, ch);
  char *result_etalon = strrchr(str, ch);
  ck_assert_ptr_eq(result, result_etalon);
}
END_TEST

START_TEST(s21_strrchr_test_6) {
  char str[] = "\0";
  char ch = 'c';
  char *result = s21_strrchr(str, ch);
  char *result_etalon = strrchr(str, ch);
  ck_assert_ptr_eq(result, result_etalon);
}
END_TEST

START_TEST(s21_strrchr_test_7) {
  char str[] = "\0\0\0\0\0\0 !@#$%^&*() qweasdzxc 123456789g sZc";
  char ch = 'c';
  char *result = s21_strrchr(str, ch);
  char *result_etalon = strrchr(str, ch);
  ck_assert_ptr_eq(result, result_etalon);
}
END_TEST

START_TEST(s21_strrchr_test_8) {
  char str[] = "!@#$%^&*()_+";
  char ch = '+';
  char *result = s21_strrchr(str, ch);
  char *result_etalon = strrchr(str, ch);
  ck_assert_ptr_eq(result, result_etalon);
}
END_TEST

START_TEST(s21_strrchr_test_9) {
  char str[] = "!@#$%^&*()_+";
  char ch = '\0';
  char *result = s21_strrchr(str, ch);
  char *result_etalon = strrchr(str, ch);
  ck_assert_ptr_eq(result, result_etalon);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, s21_strrchr_test_1);
  tcase_add_test(tc1_1, s21_strrchr_test_2);
  tcase_add_test(tc1_1, s21_strrchr_test_3);
  tcase_add_test(tc1_1, s21_strrchr_test_4);
  tcase_add_test(tc1_1, s21_strrchr_test_5);
  tcase_add_test(tc1_1, s21_strrchr_test_6);
  tcase_add_test(tc1_1, s21_strrchr_test_7);
  tcase_add_test(tc1_1, s21_strrchr_test_8);
  tcase_add_test(tc1_1, s21_strrchr_test_9);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
