/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "string_tests_check/s21_strlen_test.check"
 * instead.
 */

#include <check.h>
#include <stdio.h>
#include <string.h>

#include "../s21_string.h"

START_TEST(s21_strlen_test_1) {
  char str1[] = "There is a destination string for checking!!!!";
  size_t result = s21_strlen(str1);
  size_t result_etalon = strlen(str1);
  ck_assert_uint_eq(result, result_etalon);
}
END_TEST

START_TEST(s21_strlen_test_2) {
  char str1[] = "There is a destination\0 string for checking!!!!";
  size_t result = s21_strlen(str1);
  size_t result_etalon = strlen(str1);
  ck_assert_uint_eq(result, result_etalon);
}
END_TEST

START_TEST(s21_strlen_test_3) {
  char str1[] = "";
  size_t result = s21_strlen(str1);
  size_t result_etalon = strlen(str1);
  ck_assert_uint_eq(result, result_etalon);
}
END_TEST

START_TEST(s21_strlen_test_4) {
  char str1[] =
      " _aaa _bbb_ ccc__  312613argaGH;gn46q1346q1463 !@#$%^&*() 1234567890 ";
  size_t result = s21_strlen(str1);
  size_t result_etalon = strlen(str1);
  ck_assert_uint_eq(result, result_etalon);
}
END_TEST

START_TEST(s21_strlen_test_5) {
  char str1[] = "\0";
  size_t result = s21_strlen(str1);
  size_t result_etalon = strlen(str1);
  ck_assert_uint_eq(result, result_etalon);
}
END_TEST

START_TEST(s21_strlen_test_6) {
  char str1[] = "\0\0\0\0\0\0\0\0";
  size_t result = s21_strlen(str1);
  size_t result_etalon = strlen(str1);
  ck_assert_uint_eq(result, result_etalon);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, s21_strlen_test_1);
  tcase_add_test(tc1_1, s21_strlen_test_2);
  tcase_add_test(tc1_1, s21_strlen_test_3);
  tcase_add_test(tc1_1, s21_strlen_test_4);
  tcase_add_test(tc1_1, s21_strlen_test_5);
  tcase_add_test(tc1_1, s21_strlen_test_6);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
