/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "string_tests_check/s21_memcmp_test.check"
 * instead.
 */

#include <check.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "../s21_string.h"

START_TEST(memcmp1) {
  char str1[] = "Hello world";
  char str2[] = "Hello world";
  s21_size_t n1 = 10;
  ck_assert_int_eq(s21_memcmp(str1, str2, n1), memcmp(str1, str2, n1));
}
END_TEST

START_TEST(memcmp2) {
  char str1[] = "Hello world";
  char str2[] = "Hell0 world";
  s21_size_t n1 = 10;
  ck_assert_int_eq(s21_memcmp(str1, str2, n1), memcmp(str1, str2, n1));
}
END_TEST

START_TEST(memcmp3) {
  char str1[] = "Hello world";
  char str2[] = "Hell\0world";
  s21_size_t n1 = 10;
  ck_assert_int_eq(s21_memcmp(str1, str2, n1), memcmp(str1, str2, n1));
}
END_TEST

START_TEST(memcmp4) {
  char str1[] = "1Hello world";
  char str2[] = "Hell\0world";
  s21_size_t n1 = 11;
  ck_assert_int_eq(s21_memcmp(str1, str2, n1), memcmp(str1, str2, n1));
}
END_TEST

START_TEST(memcmp5) {
  char str1[] = "Hello world";
  char str2[] = "Hell\0world";
  s21_size_t n1 = 2;
  ck_assert_int_eq(s21_memcmp(str1, str2, n1), memcmp(str1, str2, n1));
}
END_TEST

START_TEST(memcmp6) {
  char str1[] = "Hello world";
  char str2[] = "Hellworld";
  s21_size_t n1 = 10;
  ck_assert_int_eq(s21_memcmp(str1, str2, n1), memcmp(str1, str2, n1));
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, memcmp1);
  tcase_add_test(tc1_1, memcmp2);
  tcase_add_test(tc1_1, memcmp3);
  tcase_add_test(tc1_1, memcmp4);
  tcase_add_test(tc1_1, memcmp5);
  tcase_add_test(tc1_1, memcmp6);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
