/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "string_tests_check/s21_memchr_test.check"
 * instead.
 */

#include <check.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "../s21_string.h"

START_TEST(memchr1) {
  char str1[] = "Hello world";
  s21_size_t n1 = 10;
  int ch1 = 'e';
  ck_assert_ptr_eq(s21_memchr(str1, ch1, n1), memchr(str1, ch1, n1));
}
END_TEST

START_TEST(memchr2) {
  char str2[] = "Hello world";
  s21_size_t n2 = 10;
  int ch2 = 'x';
  ck_assert_ptr_eq(s21_memchr(str2, ch2, n2), memchr(str2, ch2, n2));
}
END_TEST

START_TEST(memchr3) {
  char str3[] = "Hello world";
  s21_size_t n3 = 15;
  int ch3 = 'x';
  ck_assert_ptr_eq(s21_memchr(str3, ch3, n3), memchr(str3, ch3, n3));
}
END_TEST

START_TEST(memchr4) {
  char str4[] = "Hello\0world";
  s21_size_t n4 = 10;
  int ch4 = 'o';
  ck_assert_ptr_eq(s21_memchr(str4, ch4, n4), memchr(str4, ch4, n4));
}
END_TEST

START_TEST(memchr5) {
  char str5[] = "Hello\0world";
  s21_size_t n5 = 10;
  int ch5 = 'w';
  ck_assert_ptr_eq(s21_memchr(str5, ch5, n5), memchr(str5, ch5, n5));
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, memchr1);
  tcase_add_test(tc1_1, memchr2);
  tcase_add_test(tc1_1, memchr3);
  tcase_add_test(tc1_1, memchr4);
  tcase_add_test(tc1_1, memchr5);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
