/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "string_tests_check/s21_strtok_test.check"
 * instead.
 */

#include <check.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "../s21_string.h"

START_TEST(s21_strtok_test_1) {
  int n = 4;
  char str1[] = "_afga ___aers@asr___sweer__";
  char str2[] = "_afga ___aers@asr___sweer__";
  const char vp[] = "_ ! @";

  char *token = s21_strtok(str1, vp);
  char *token_etalon = strtok(str2, vp);
  ck_assert_pstr_eq(token, token_etalon);

  for (int i = 0; i < n; i++) {
    token = s21_strtok(s21_NULL, vp);
    token_etalon = strtok(s21_NULL, vp);
    ck_assert_pstr_eq(token, token_etalon);
  }
}
END_TEST

START_TEST(s21_strtok_test_2) {
  int n = 4;
  char str1[] = "_afga ___ae\0s@asr___sweer__";
  char str2[] = "_afga ___ae\0s@asr___sweer__";
  const char vp[] = "_ ! @";

  char *token = s21_strtok(str1, vp);
  char *token_etalon = strtok(str2, vp);
  ck_assert_pstr_eq(token, token_etalon);

  for (int i = 0; i < n; i++) {
    token = s21_strtok(s21_NULL, vp);
    token_etalon = strtok(s21_NULL, vp);
    ck_assert_pstr_eq(token, token_etalon);
  }
}
END_TEST

START_TEST(s21_strtok_test_3) {
  int n = 4;
  char str1[] = "_afga ___ae\0s@asr___sweer__";
  char str2[] = "_afga ___ae\0s@asr___sweer__";
  const char vp[] = "?";

  char *token = s21_strtok(str1, vp);
  char *token_etalon = strtok(str2, vp);
  ck_assert_pstr_eq(token, token_etalon);

  for (int i = 0; i < n; i++) {
    token = s21_strtok(s21_NULL, vp);
    token_etalon = strtok(s21_NULL, vp);
    ck_assert_pstr_eq(token, token_etalon);
  }
}
END_TEST

START_TEST(s21_strtok_test_4) {
  int n = 6;
  char str1[] = "";
  char str2[] = "";
  const char vp[] = "";

  char *token = s21_strtok(str1, vp);
  char *token_etalon = strtok(str2, vp);
  ck_assert_pstr_eq(token, token_etalon);

  for (int i = 0; i < n; i++) {
    token = s21_strtok(s21_NULL, vp);
    token_etalon = strtok(s21_NULL, vp);
    ck_assert_pstr_eq(token, token_etalon);
  }
}
END_TEST

START_TEST(s21_strtok_test_5) {
  int n = 10;
  char str1[] = "";
  char str2[] = "";
  const char vp[] = " !_";

  char *token = s21_strtok(str1, vp);
  char *token_etalon = strtok(str2, vp);
  ck_assert_pstr_eq(token, token_etalon);

  for (int i = 0; i < n; i++) {
    token = s21_strtok(s21_NULL, vp);
    token_etalon = strtok(s21_NULL, vp);
    ck_assert_pstr_eq(token, token_etalon);
  }
}
END_TEST

START_TEST(s21_strtok_test_6) {
  int n = 7;
  char str1[] = "_afga ___aers@asr___sweer__";
  char str2[] = "_afga ___aers@asr___sweer__";
  const char vp[] = "";

  char *token = s21_strtok(str1, vp);
  char *token_etalon = strtok(str2, vp);
  ck_assert_pstr_eq(token, token_etalon);

  for (int i = 0; i < n; i++) {
    token = s21_strtok(s21_NULL, vp);
    token_etalon = strtok(s21_NULL, vp);
    ck_assert_pstr_eq(token, token_etalon);
  }
}
END_TEST

START_TEST(s21_strtok_test_7) {
  int n = 4;
  char str1[] = "_afga ___aers@asr___sweer__";
  char str2[] = "_afga ___aers@asr___sweer__";
  const char vp[] = "\0";

  char *token = s21_strtok(str1, vp);
  char *token_etalon = strtok(str2, vp);
  ck_assert_pstr_eq(token, token_etalon);

  for (int i = 0; i < n; i++) {
    token = s21_strtok(s21_NULL, vp);
    token_etalon = strtok(s21_NULL, vp);
    ck_assert_pstr_eq(token, token_etalon);
  }
}
END_TEST

START_TEST(s21_strtok_test_8) {
  int n = 10;
  char str1[] = "\0\0";
  char str2[] = "\0\0";
  const char vp[] = "\0";

  char *token = s21_strtok(str1, vp);
  char *token_etalon = strtok(str2, vp);
  ck_assert_pstr_eq(token, token_etalon);

  for (int i = 0; i < n; i++) {
    token = s21_strtok(s21_NULL, vp);
    token_etalon = strtok(s21_NULL, vp);
    ck_assert_pstr_eq(token, token_etalon);
  }
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, s21_strtok_test_1);
  tcase_add_test(tc1_1, s21_strtok_test_2);
  tcase_add_test(tc1_1, s21_strtok_test_3);
  tcase_add_test(tc1_1, s21_strtok_test_4);
  tcase_add_test(tc1_1, s21_strtok_test_5);
  tcase_add_test(tc1_1, s21_strtok_test_6);
  tcase_add_test(tc1_1, s21_strtok_test_7);
  tcase_add_test(tc1_1, s21_strtok_test_8);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
