/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "string_tests_check/s21_strncmp_test.check"
 * instead.
 */

#include <check.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "../s21_string.h"

START_TEST(s21_strncmp_test_1) {
  char str1[] = "There is a destination string for checking!!!!";
  char str2[] = "There is a destination string for checking!!!!";
  s21_size_t n = 10;
  int result = s21_strncmp(str1, str2, n);
  int result_etalon = strncmp(str1, str2, n);
  ck_assert_int_eq(result, result_etalon);
}
END_TEST

START_TEST(s21_strncmp_test_2) {
  char str1[] = "There is a destination string..";
  char str2[] = "There is a destination string for checking!!!!";
  s21_size_t n = 10;
  int result = s21_strncmp(str1, str2, n);
  int result_etalon = strncmp(str1, str2, n);
  ck_assert_int_eq(result, result_etalon);
}
END_TEST

START_TEST(s21_strncmp_test_3) {
  char str1[] = "There is a destination string for checking!!!!";
  char str2[] = "There is a destination string..";
  s21_size_t n = 10;
  int result = s21_strncmp(str1, str2, n);
  int result_etalon = strncmp(str1, str2, n);
  ck_assert_int_eq(result, result_etalon);
}
END_TEST

START_TEST(s21_strncmp_test_4) {
  char str1[] = "";
  char str2[] = "";
  s21_size_t n = 10;
  int result = s21_strncmp(str1, str2, n);
  int result_etalon = strncmp(str1, str2, n);
  ck_assert_int_eq(result, result_etalon);
}
END_TEST

START_TEST(s21_strncmp_test_5) {
  char str1[] = "There is a destination string for checking!!!!";
  char str2[] = "There is a destination string \0..";
  s21_size_t n = 10;
  int result = s21_strncmp(str1, str2, n);
  int result_etalon = strncmp(str1, str2, n);
  ck_assert_int_eq(result, result_etalon);
}
END_TEST

START_TEST(s21_strncmp_test_6) {
  char str1[] = "There is a destination string\0 for checking!!!!";
  char str2[] = "There is a destination string..";
  s21_size_t n = 10;
  int result = s21_strncmp(str1, str2, n);
  int result_etalon = strncmp(str1, str2, n);
  ck_assert_int_eq(result, result_etalon);
}
END_TEST

START_TEST(s21_strncmp_test_7) {
  char str1[] = "There is a destination string\0 for checking!!!!";
  char str2[] = "There is a destination string\0 ..";
  s21_size_t n = 10;
  int result = s21_strncmp(str1, str2, n);
  int result_etalon = strncmp(str1, str2, n);
  ck_assert_int_eq(result, result_etalon);
}
END_TEST

START_TEST(s21_strncmp_test_8) {
  char str1[] = "!@#$%^&*()*(&%#%@$#!@)";
  char str2[] = "!@#$%^&*()*   (&%#%@$#!@)";
  s21_size_t n = 10;
  int result = s21_strncmp(str1, str2, n);
  int result_etalon = strncmp(str1, str2, n);
  ck_assert_int_eq(result, result_etalon);
}
END_TEST

START_TEST(s21_strncmp_test_9) {
  char str1[] = "!@#$%^&*()*(&%#%@$#!@)";
  char str2[] = "!@#$%^&*()*   (&%#%@$#!@)";
  s21_size_t n = 0;
  int result = s21_strncmp(str1, str2, n);
  int result_etalon = strncmp(str1, str2, n);
  ck_assert_int_eq(result, result_etalon);
}
END_TEST

START_TEST(s21_strncmp_test_10) {
  char str1[] = "";
  char str2[] = "";
  s21_size_t n = 0;
  int result = s21_strncmp(str1, str2, n);
  int result_etalon = strncmp(str1, str2, n);
  ck_assert_int_eq(result, result_etalon);
}
END_TEST

START_TEST(s21_strncmp_test_11) {
  char str1[] = "";
  char str2[] = "";
  s21_size_t n = 5;
  int result = s21_strncmp(str1, str2, n);
  int result_etalon = strncmp(str1, str2, n);
  ck_assert_int_eq(result, result_etalon);
}
END_TEST

START_TEST(s21_strncmp_test_12) {
  char str1[] = "/0/0/0/0/0/0";
  char str2[] = "/0/0/0/0/0/0";
  s21_size_t n = 5;
  int result = s21_strncmp(str1, str2, n);
  int result_etalon = strncmp(str1, str2, n);
  ck_assert_int_eq(result, result_etalon);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, s21_strncmp_test_1);
  tcase_add_test(tc1_1, s21_strncmp_test_2);
  tcase_add_test(tc1_1, s21_strncmp_test_3);
  tcase_add_test(tc1_1, s21_strncmp_test_4);
  tcase_add_test(tc1_1, s21_strncmp_test_5);
  tcase_add_test(tc1_1, s21_strncmp_test_6);
  tcase_add_test(tc1_1, s21_strncmp_test_7);
  tcase_add_test(tc1_1, s21_strncmp_test_8);
  tcase_add_test(tc1_1, s21_strncmp_test_9);
  tcase_add_test(tc1_1, s21_strncmp_test_10);
  tcase_add_test(tc1_1, s21_strncmp_test_11);
  tcase_add_test(tc1_1, s21_strncmp_test_12);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
